
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 12.4 EDK_MS4.81d
* DO NOT EDIT.
*
* Copyright (c) 1995-2010 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_BUTTONS_3BIT_DEVICE_ID,
		XPAR_BUTTONS_3BIT_BASEADDR,
		XPAR_BUTTONS_3BIT_INTERRUPT_PRESENT,
		XPAR_BUTTONS_3BIT_IS_DUAL
	},
	{
		XPAR_CHARACTER_LCD_2X16_DEVICE_ID,
		XPAR_CHARACTER_LCD_2X16_BASEADDR,
		XPAR_CHARACTER_LCD_2X16_INTERRUPT_PRESENT,
		XPAR_CHARACTER_LCD_2X16_IS_DUAL
	},
	{
		XPAR_DIP_SWITCHES_4BIT_DEVICE_ID,
		XPAR_DIP_SWITCHES_4BIT_BASEADDR,
		XPAR_DIP_SWITCHES_4BIT_INTERRUPT_PRESENT,
		XPAR_DIP_SWITCHES_4BIT_IS_DUAL
	},
	{
		XPAR_LEDS_8BIT_DEVICE_ID,
		XPAR_LEDS_8BIT_BASEADDR,
		XPAR_LEDS_8BIT_INTERRUPT_PRESENT,
		XPAR_LEDS_8BIT_IS_DUAL
	},
	{
		XPAR_ROTARY_ENCODER_DEVICE_ID,
		XPAR_ROTARY_ENCODER_BASEADDR,
		XPAR_ROTARY_ENCODER_INTERRUPT_PRESENT,
		XPAR_ROTARY_ENCODER_IS_DUAL
	}
};


