#################################################################
# Makefile generated by Xilinx Platform Studio 
# Project:\\vboxsvr\real-pc\Trabajo\CUJAE\SPE\SPE-2023\examples\ex_3\system.xmp
#
# WARNING : This file will be re-generated every time a command
# to run a make target is invoked. So, any changes made to this  
# file manually, will be lost when make is invoked next. 
#################################################################

XILINX_EDK_DIR = /cygdrive/c/Xilinx/12.4/ISE_DS/EDK
NON_CYG_XILINX_EDK_DIR = C:/Xilinx/12.4/ISE_DS/EDK

SYSTEM = system

MHSFILE = system.mhs

MSSFILE = system.mss

FPGA_ARCH = spartan3e

DEVICE = xc3s1600efg320-4

LANGUAGE = vhdl
GLOBAL_SEARCHPATHOPT = 
PROJECT_SEARCHPATHOPT = 

SEARCHPATHOPT = $(PROJECT_SEARCHPATHOPT) $(GLOBAL_SEARCHPATHOPT)

SUBMODULE_OPT = 

PLATGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(SUBMODULE_OPT) -msg __xps/ise/xmsgprops.lst

LIBGEN_OPTIONS = -mhs $(MHSFILE) -p $(DEVICE) $(SEARCHPATHOPT) -msg __xps/ise/xmsgprops.lst \
                   $(MICROBLAZE_0_LIBG_OPT)

OBSERVE_PAR_OPTIONS = -error yes

EX_TIMER_OUTPUT_DIR = ex_timer
EX_TIMER_OUTPUT = $(EX_TIMER_OUTPUT_DIR)/executable.elf
CYG_EX_TIMER_OUTPUT_DIR = ex_timer
CYG_EX_TIMER_OUTPUT = $(CYG_EX_TIMER_OUTPUT_DIR)/executable.elf

MICROBLAZE_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop.elf
MICROBLAZE_BOOTLOOP_LE = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop_le.elf
PPC405_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc405/ppc_bootloop.elf
PPC440_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc440/ppc440_bootloop.elf
BOOTLOOP_DIR = bootloops

MICROBLAZE_0_BOOTLOOP = $(BOOTLOOP_DIR)/microblaze_0.elf
MICROBLAZE_0_XMDSTUB = microblaze_0/code/xmdstub.elf

BRAMINIT_ELF_FILES =  
BRAMINIT_ELF_FILE_ARGS =  

ALL_USER_ELF_FILES = $(CYG_EX_TIMER_OUTPUT) 

SIM_CMD = ./isim_system

BEHAVIORAL_SIM_SCRIPT = simulation/behavioral/$(SYSTEM)_setup.tcl

STRUCTURAL_SIM_SCRIPT = simulation/structural/$(SYSTEM)_setup.tcl

TIMING_SIM_SCRIPT = simulation/timing/$(SYSTEM)_setup.tcl

DEFAULT_SIM_SCRIPT = $(BEHAVIORAL_SIM_SCRIPT)

MIX_LANG_SIM_OPT = -mixed no

SIMGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(BRAMINIT_ELF_FILE_ARGS) $(MIX_LANG_SIM_OPT) -msg __xps/ise/xmsgprops.lst -sd implementation/ -s isim -X Z:/Trabajo/CUJAE/SPE/SPE-2023/examples/ex_3/


LIBRARIES =  \
       microblaze_0/lib/libxil.a 

LIBSCLEAN_TARGETS = microblaze_0_libsclean 

PROGRAMCLEAN_TARGETS = ex_timer_programclean 

CORE_STATE_DEVELOPMENT_FILES = 

WRAPPER_NGC_FILES = implementation/microblaze_0_wrapper.ngc \
implementation/mb_plb_wrapper.ngc \
implementation/ilmb_wrapper.ngc \
implementation/dlmb_wrapper.ngc \
implementation/dlmb_cntlr_wrapper.ngc \
implementation/ilmb_cntlr_wrapper.ngc \
implementation/lmb_bram_wrapper.ngc \
implementation/leds_8bit_wrapper.ngc \
implementation/dip_switches_4bit_wrapper.ngc \
implementation/buttons_3bit_wrapper.ngc \
implementation/character_lcd_2x16_wrapper.ngc \
implementation/rotary_encoder_wrapper.ngc \
implementation/ddr_sdram_wrapper.ngc \
implementation/rs232_dce_wrapper.ngc \
implementation/xps_timer_0_wrapper.ngc \
implementation/clock_generator_0_wrapper.ngc \
implementation/mdm_0_wrapper.ngc \
implementation/proc_sys_reset_0_wrapper.ngc \
implementation/xps_intc_0_wrapper.ngc

POSTSYN_NETLIST = implementation/$(SYSTEM).ngc

SYSTEM_BIT = implementation/$(SYSTEM).bit

DOWNLOAD_BIT = implementation/download.bit

SYSTEM_ACE = implementation/$(SYSTEM).ace

UCF_FILE = data/system.ucf

BMM_FILE = implementation/$(SYSTEM).bmm

BITGEN_UT_FILE = etc/bitgen.ut

XFLOW_OPT_FILE = etc/fast_runtime.opt
XFLOW_DEPENDENCY = __xps/xpsxflow.opt $(XFLOW_OPT_FILE)

XPLORER_DEPENDENCY = __xps/xplorer.opt
XPLORER_OPTIONS = -p $(DEVICE) -uc $(SYSTEM).ucf -bm $(SYSTEM).bmm -max_runs 7

FPGA_IMP_DEPENDENCY = $(BMM_FILE) $(POSTSYN_NETLIST) $(UCF_FILE) $(XFLOW_DEPENDENCY)

# cygwin path for windows
SDK_EXPORT_DIR = SDK/SDK_Export/hw
CYG_SDK_EXPORT_DIR = SDK/SDK_Export/hw
SYSTEM_HW_HANDOFF = $(SDK_EXPORT_DIR)/$(SYSTEM).xml
CYG_SYSTEM_HW_HANDOFF = $(CYG_SDK_EXPORT_DIR)/$(SYSTEM).xml
SYSTEM_HW_HANDOFF_BIT = $(SDK_EXPORT_DIR)/$(SYSTEM).bit
CYG_SYSTEM_HW_HANDOFF_BIT = $(CYG_SDK_EXPORT_DIR)/$(SYSTEM).bit
SYSTEM_HW_HANDOFF_BMM = $(SDK_EXPORT_DIR)/$(SYSTEM)_bd.bmm
CYG_SYSTEM_HW_HANDOFF_BMM = $(CYG_SDK_EXPORT_DIR)/$(SYSTEM)_bd.bmm
SYSTEM_HW_HANDOFF_DEP = $(CYG_SYSTEM_HW_HANDOFF) $(CYG_SYSTEM_HW_HANDOFF_BIT) $(CYG_SYSTEM_HW_HANDOFF_BMM)

#################################################################
# SOFTWARE APPLICATION EX_TIMER
#################################################################

EX_TIMER_SOURCES = ex_timer/src/main.c 

EX_TIMER_HEADERS = 

EX_TIMER_CC = mb-gcc
EX_TIMER_CC_SIZE = mb-size
EX_TIMER_CC_OPT = -O0
EX_TIMER_CFLAGS = 
EX_TIMER_CC_SEARCH = # -B
EX_TIMER_LIBPATH = -L./microblaze_0/lib/ # -L
EX_TIMER_INCLUDES = -I./microblaze_0/include/ # -I
EX_TIMER_LFLAGS = # -l
EX_TIMER_LINKER_SCRIPT = ex_timer/ex_timer_linker_script.ld
EX_TIMER_LINKER_SCRIPT_FLAG = -T $(EX_TIMER_LINKER_SCRIPT) 
EX_TIMER_CC_DEBUG_FLAG =  -g 
EX_TIMER_CC_PROFILE_FLAG = # -pg
EX_TIMER_CC_GLOBPTR_FLAG= # -mxl-gp-opt
EX_TIMER_MODE = executable
EX_TIMER_LIBG_OPT = -$(EX_TIMER_MODE) microblaze_0
EX_TIMER_CC_INFERRED_FLAGS= -mxl-soft-mul -mxl-barrel-shift -mxl-pattern-compare -mcpu=v8.00.b 
EX_TIMER_CC_START_ADDR_FLAG=  #  # -Wl,-defsym -Wl,_TEXT_START_ADDR=
EX_TIMER_CC_STACK_SIZE_FLAG=  #  # -Wl,-defsym -Wl,_STACK_SIZE=
EX_TIMER_CC_HEAP_SIZE_FLAG=  #  # -Wl,-defsym -Wl,_HEAP_SIZE=
EX_TIMER_OTHER_CC_FLAGS= $(EX_TIMER_CC_GLOBPTR_FLAG)  \
                  $(EX_TIMER_CC_START_ADDR_FLAG) $(EX_TIMER_CC_STACK_SIZE_FLAG) $(EX_TIMER_CC_HEAP_SIZE_FLAG)  \
                  $(EX_TIMER_CC_INFERRED_FLAGS)  \
                  $(EX_TIMER_LINKER_SCRIPT_FLAG) $(EX_TIMER_CC_DEBUG_FLAG) $(EX_TIMER_CC_PROFILE_FLAG) 
